### ISSUE TITLE
Break Things Fast: Accelerated QA and Testing with Upsun

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2024-talks#10]
Hello @gregqualls

Would it be possible for you to share your slides, please?
And if you have a blog post about it too, it would be awesome!

<img src="https://media1.giphy.com/media/tKxK0jHpKWiemOKqc5/giphy.gif"/>

**Comment by gregqualls** [comment]
Hey @mykiwi 

Here is a link to [my deck](https://docs.google.com/presentation/d/1Pz8wZKB_mZ3XVS4mmOXuBK4R8ps1nbrJpvXaXqKV4lM/edit?usp=sharing).

There isn't a blog post from me, but there are several on cloned environments in the [Upsun DevCenter](https://devcenter.upsun.com/).

Here are two in particular:

[Preview Environments - A Developer’s Secret Weapon](https://devcenter.upsun.com/posts/preview-environments-a-developers-secret-weapon/#but-what-do-you-need-to-make-this-happen)

[What is instant data cloning? The game changer for developing cloud-based applications ](https://upsun.com/blog/data-cloning-the-game-changer-for-developing-cloud-based-applications/)

Hope that helps.

I also understand the video of my talk will be out pretty soon as well.
