### ISSUE TITLE
Composer Behind the Scenes

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2024-talks#12]
Hello @naderman

Would it be possible for you to share your slides, please?
And if you have a blog post about it too, it would be awesome!

<img src="https://media0.giphy.com/media/ZfK4cXKJTTay1Ava29/giphy.gif"/>

**Comment by naderman** [comment]
@mykiwi They are here now: https://naderman.de/slippy/slides/2024-12-05-SymfonyCon-Vienna-Composer-Behind-the-Scenes.pdf
