### ISSUE TITLE
Designing for Change: Extensibility points in practice

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2024-talks#14]
Hello @adamwojs

Would it be possible for you to share your slides, please?
And if you have a blog post about it too, it would be awesome!

<img src="https://media3.giphy.com/media/26gsjCZpPolPr3sBy/giphy.gif"/>

**Comment by adamwojs** [comment]
Hi @mykiwi! 

I've uploaded my slides to https://speakerdeck.com/adamwojs/designing-for-change-extensibility-points-in-practice and attached the link to https://live.symfony.com/
