### ISSUE TITLE
The missing Gotenberg Bundle. Components, Assemble!

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2024-talks#16]
Hello @Neirda24 & @Jean-Beru

Would it be possible for you to share your slides, please?
And if you have a blog post about it too, it would be awesome!

<img src="https://media4.giphy.com/media/RIhNQOjGa39Ze/giphy.gif"/>

**Comment by Neirda24** [comment]
Hi. Here are the slides : https://neirda24.github.io/talk-sfcon-2024-vienna-gotenberg/1 (already published on Symfony website normally...) The article we have is from @StevenRenaux here : https://medium.com/the-sensiolabs-tech-blog/how-to-generate-a-pdf-file-in-a-few-lines-of-code-with-symfony-39786a679d29

Would that suits you ?

**Comment by mykiwi** [comment]
> slides [already published on Symfony website normally...

Are they visible? because I don't find them on https://live.symfony.com/2024-vienna-con/

**Comment by Jean-Beru** [comment]
Hello @mykiwi,

Slides are available on the [Conference Replay](https://live.symfony.com/account/replay/videos/2024-vienna-con) page.

See you at the SymfonyLive2025! (I hope)
