### ISSUE TITLE
Bulletproofing for Black Friday

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2024-talks#18]
Hello @thomasdiluccio

Would it be possible for you to share your slides, please?
And if you have a blog post about it too, it would be awesome!

<img src="https://media0.giphy.com/media/BYoRqTmcgzHcL9TCy1/giphy.gif"/>

**Comment by thomasdiluccio** [comment]
Hi @mykiwi! Here are the slides: https://speakerdeck.com/thomasdiluccio/bulletproofing-for-black-friday-symfonycon-vienna-2024

As for blog post, It's the chicken and egg situation. I'm waiting for the recordings to be available to publish one. I'll keep you posted!

Thanks a lot for putting this repo together!
