### ISSUE TITLE
Crafting a Microservice That Fits Your Needs

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2024-talks#19]
Hello @hayleemillar

Would it be possible for you to share your slides, please?
And if you have a blog post about it too, it would be awesome!

<img src="https://media4.giphy.com/media/l2R0cAF1y9a9ngCLS/giphy.gif"/>

**Comment by hayleemillar** [comment]
Hello 👋🏻 
Sure thing. You can find them [here](https://speakerdeck.com/hayleemillar/symfonycon-vienna-2024). No blog post but if one does happen, I know now to come back. Thanks!
