### ISSUE TITLE
Symfony Notifier : Return of the Mailman

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2024-talks#20]
Hello @raphael-geffroy

Would it be possible for you to share your slides, please?
And if you have a blog post about it too, it would be awesome!

<img src="https://media1.giphy.com/media/tKxK0jHpKWiemOKqc5/giphy.gif"/>

**Comment by raphael-geffroy** [comment]
Here they are : https://slides.com/raphael-geffroy/symfony-notifier-return-of-the-mailman. Sorry for the delay and thank you for your work 🙏
