### ISSUE TITLE
Resurrecting the Dead

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2024-talks#23]
Hello @jrfnl

Would it be possible for you to share your slides, please?
And if you have a blog post about it too, it would be awesome!

<img src="https://media0.giphy.com/media/ZfK4cXKJTTay1Ava29/giphy.gif"/>

**Comment by jrfnl** [comment]
@mykiwi I already did on the official SymfonyCon website + they are up on speakerdeck. And I don't blog for anybody.
