### ISSUE TITLE
Revolutionize Searchandising with Gally!

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2024-talks#25]
Hello @romainruaud

Would it be possible for you to share your slides, please?
And if you have a blog post about it too, it would be awesome!

<img src="https://media1.giphy.com/media/fYezwj2HyoYbJKIreV/giphy.gif"/>

**Comment by romainruaud** [comment]
Hi @mykiwi my slidedeck is here : https://speakerdeck.com/romainruaud/2024-gally-at-symfonycon-revolutionize-searchandising-with-gally

Regards
