### ISSUE TITLE
Running Symfony in a Multi-Process Container

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2024-talks#26]
Hello @dazz

Would it be possible for you to share your slides, please?
And if you have a blog post about it too, it would be awesome!

<img src="https://media3.giphy.com/media/4JEqHjhfSnXOcRsfMr/giphy.gif"/>

**Comment by dazz** [comment]
hey @mykiwi 
here are the slides: https://speakerdeck.com/dazz/running-symfony-in-a-multi-process-container-symfonycon-vienna-2024

there is no blog-post, yet
