### ISSUE TITLE
Code Less, Create More: Unleashing AI Secret Weapons for Lazy(?) Developers!

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2024-talks#27]
Hello @clawfire

Would it be possible for you to share your slides, please?
And if you have a blog post about it too, it would be awesome!

<img src="https://media2.giphy.com/media/T9JtEyoJ43gY4wLOqW/giphy.gif"/>

**Comment by clawfire** [comment]
hoooooo sooo cool there's an issue for ... wait ... that repo is so cool 🤩 

Slides [are on my Spearkerdeck](https://speakerdeck.com/thibaultmilan/code-less-create-more-unleashing-ai-secret-weapons-for-lazy-developers) but I can add a .pdf file here if it's the common way of doing it. 

I've planned to make a blogpost about the event too before XMAS 🎄.
