### ISSUE TITLE
Modern Approaches to Web Security: Stateless CSRF Protection Explained

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2024-talks#28]
Hello @nicolas-grekas

Would it be possible for you to share your slides, please?
And if you have a blog post about it too, it would be awesome!

<img src="https://media3.giphy.com/media/KvAKXViNfpU8fSDiF0/giphy.gif"/>

**Comment by nicolas-grekas** [comment]
Here you are: https://speakerdeck.com/nicolasgrekas/modern-approaches-to-web-security-stateless-csrf-protection-explained
