### ISSUE TITLE
Building a Fraud Prevention component using Symfony

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2024-talks#5]
Hello @moritzschuh

Would it be possible for you to share your slides, please?
And if you have a blog post about it too, it would be awesome!

<img src="https://media0.giphy.com/media/aBX76zqhKX7LaoY95k/giphy.gif"/>

**Comment by moritzschuh** [comment]
Hi Romain,

Thank you for your interest in my talk!

I have now uploaded and attached my sides, you can find them in the
SymfonyCon Vienna Replay section.
Also, here's a direct link:
https://docs.google.com/presentation/d/e/2PACX-1vR5aKfFNnB2zoWoF0P3VpPBGjkazsN2RRqmnKMtgMJE0la5sgc8aLeCMK1kDutcZ0M7WLWVZj8kHkYw/pub?start=false&loop=false&delayms=3000

Unfortunately, I don't have a blog post ready at this time, but I'll make
sure to add it here, should I write one in the near future.

Best wishes,
Moritz

--

Moritz Schuh // Product Engineer

https://platform.sh
<https://www.google.com/url?q=http://platform.sh/&sa=D&source=editors&ust=1654509389386081&usg=AOvVaw1DsmQPgl8MRguDbue14olh>
