### ISSUE TITLE
Who did that? Auditing data changes at scale

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2024-talks#8]
Hello @splagemann

Would it be possible for you to share your slides, please?
And if you have a blog post about it too, it would be awesome!

<img src="https://media3.giphy.com/media/RgOKyNiw9wYaztbveu/giphy.gif"/>

**Comment by splagemann** [comment]
Here they are https://basti.dev/talks/20241205_SymfonyCon_Vienna_Auditing_Data_Changes.pdf
